## Configuración de Spring
spring:
  application:
    name: calculator
  datasource:
    url: jdbc:h2:mem:testdb;Mode=MySQL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

## Configuración de Instancia
server:
  port: 8088